id: I282DD2DF
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:44.969628
last_modified: 2023-01-04 11:30:44.969641
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  CC97:
    title: A Profound and Concise Guru Yoga
    base_file: CC97.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
